### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by LoicGoyet** [Trowel/trowel.github.io#3]
* [*homepage*]  The Trowel variables allow**s** you (remove the "s")
* [*homepage*]  "This pattern allows the user to totally control the css output, by generating only the style required. CSS framework will no more be big boats, they will just fit for you website." => "This pattern allows the user to totally control the **CSS** output, by generating only the style required. CSS framework**s** will no more be big boats, they will just fit for you website."
* [*everywhere*] maintened => maintained
* [*everywhere*] regroups => gathers
* [*everywhere*] every basic components thats compose any CSS framework => every basic component that composes a CSS framework
* [*everywhere*] lot of Trowel variable => lot of Trowel variables
* [*title*] evolving => evolved

**Comment by paulandrieux** [comment]
[Layouts/Grids] "You can layout as grid your content," => "You can layout your content as grid"
[Layouts/Enables] "You can avoid the generation of some css with those following variables" => "You can avoid the generation of some css with *the* following variables"
[Use a trowel component] "and you use one of the official component listed in the Friends of Trowel section." => "and you *can* use one of the official component listed in the Friends of Trowel section."
